### ISSUE TITLE
BUG: MPL Deprecation warning

### ISSUE THREAD

**Issue by aburrell** [lkilcommons/ssj_auroral_boundary#11]
In CI testing, I am getting a matplotlib deprecation warning that needs to be fixed before Matplotlib 3.3 is released:

> .../ssj_auroral_boundary/abpolarpass.py:14: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  mpl.use('Agg', warn=False, force=False)

**Comment by aburrell** [comment]
This warning is now a bug.  To fix it, line 14 in `abpolarpass.py` needs to be changed to `mpl.use('Agg', force=False)`.

**Comment by lkilcommons** [comment]
Apologies, accidental close. I believe I've fixed this, but I'll wait until you confirm it works on your CI to close.

**Comment by aburrell** [comment]
I can confirm that it now works for python 2.7 and all the python 3 versions I test.  Thank you!
