### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by aburrell** [lkilcommons/ssj_auroral_boundary#5]
Unit tests are currently missing.

**Comment by lkilcommons** [comment]
I've added some fairly basic integration pytest tests (can the code find the bundled test data, read it, and does it succeed and fail to find boundaries). The design of the code makes standard unit tests a bit difficult without a ton of fixtures.

**Comment by aburrell** [comment]
It's good to see that testing has begun!  In the interest of not having issues that hang around forever, I am going to close this one out.  After all, it did only ask for *some* tests.
