### ISSUE TITLE
DOI needed

### ISSUE THREAD

**Issue by aburrell** [lkilcommons/ssj_auroral_boundary#7]
A DOI is needed so that I can cite this code properly.

**Comment by aburrell** [comment]
Pinging you on this, since I'd like to add it to a manuscript now.

**Comment by lkilcommons** [comment]
I'm moving toward a 1.0 release on this. I still need to address a few issues, then I will do a release and you can use the Github DOI for the release in your paper.

**Comment by aburrell** [comment]
Great!  Let me know if you'd like any support getting this done.  Happy to do a code review, for instance.

**Comment by lkilcommons** [comment]
Version 1 is a go!

[![DOI](https://zenodo.org/badge/154356043.svg)](https://zenodo.org/badge/latestdoi/154356043)
