### ISSUE TITLE
Another 2/3 compatibility issue in abpolarpass

### ISSUE THREAD

**Issue by aburrell** [lkilcommons/ssj_auroral_boundary#9]
I found another python 2/3 compatibility issue.

In abpolarpass function `moving_average`, integer division is used.  This behaviour has changed and can cause problems.  This can be fixed by updating the function thusly:

```
def moving_average(self,x,window_size):
        """Creates a weighted average smoothed version of x using the weights in window"""
        # Python 2 and 3 treat integer rounding differently.  Default to
        # finding the floor value (old behaviour)
        half_window = int(np.floor(0.5 * window_size))
        return np.nanmean(self.rolling_window(np.concatenate((x[:half_window],
                                                    x, x[-half_window:])),
                                              window_size), -1)
```

**Comment by lkilcommons** [comment]
Thank you Angeline...I've fixed this in my local version and will push up
with the next batch of updates.
I don't think the impact is very big (please correct me if you disagree),
and I thank you for your attention to detail. Good luck at AGU!

**Comment by aburrell** [comment]
I ran into this in my integration of the DMSP boundaries into ocbpy.  I fixed it locally, so it works for my testing right now, but once I get that bit of the branch done I will be waiting on you before releasing it.  That said, things are moving at the speed of AGU and holidays, so at the moment there's no rush!

**Comment by lkilcommons** [comment]
I've created a new branch called python3 in which I've merged these and other Python 3 compatibility changes. I'm planning this branch to be the develop branch for version 1.1, since the main feature difference will be better Python 3 support.

**Comment by aburrell** [comment]
How is this going?  I've added a unit testing branch that uses this in ocbpy.  Currently it's passing on 2.7 and failing on 3.X (as expected).  You can read the error log here: https://travis-ci.org/github/aburrell/ocbpy/builds/681600281 on the EXTRA_INSTALLS=2 runs.  Let me know if I can help.

**Comment by lkilcommons** [comment]
Sorry, this fell off my task list. My unit tests pass locally on Python 3 now. Let me know if your CI is still unhappy with it. 
Also FYI, I'm tentatively planning to switch this package over to CDFlib so I can have manageable CI.

**Comment by aburrell** [comment]
CDFlib would be great.  I'm having a really hard time installing the NASA CDF library on AppVeyor.

**Comment by lkilcommons** [comment]
FYI I am working on getting up to speed with CDFlib (lkilcommons/pycdf2cdflib). This may take a bit of time...it seems like CDFlib does not have a very stable interface, and the documentation is not well organized yet.
